name: "Build Debian Live Minimal ISO"

on:
  schedule:
  # 7AM on the 1st of every month (GitHub is GMT)
  # https://crontab.guru/#0_7_1_*_*
    - cron: "0 7 1 * *"

  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

  workflow_dispatch:

jobs:
  build-release:
    name: "Build and Release"
    runs-on: "ubuntu-24.04"
    permissions:
      contents: write

    steps:
      - name: "Get Date"
        id: get_date
        run: |
          echo "datestamp=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: "Checking out git repository"
        uses: actions/checkout@v4

      - name: "Build Image"
        run: |
          ./build.sh

      - name: "Publish"
        uses: "marvinpinto/action-automatic-releases@v1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ steps.get_date.outputs.datestamp }}"
          title: "Debian 13 Live Minimal ISO"
          files: |
            output/debian13-live-minimal-x86_64.iso
            output/packages.txt
